### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by Zulko** [OrigamiDrag0n/4D-Graphics#2]
Hey just saw that your post on Reddit was being badly received, with people talking about the post title more than the project itself (that's unfortunately very common!) and  your link to the source code being downloaded to oblivion (seriously that's weird).

I just wanted to say don't be discouraged. The project shows a lot of efforts and is very interesting in itself. I see many ways you could have improved the presentation and code (not sure about your pipeline here, looks like you are having scripts that print meshes and then you copy-paste these into files!) but if you are really 14 then that's pretty understandable (I guess getting a result is the priority here, whatever works!)

Once you learn about more tools, libraries, coding standards, etc. you'll be able to code 10x faster and cleaner, and with the amount of math understanding you are showing there, you should be pretty impressive. Your success on Reddit will still be subject to luck though!

**Comment by OrigamiDrag0n** [comment]
Thanks so much! I am working on an improved version using PIL and or NumPy (makes the matrices easier). I will keep you posted on that!

**Comment by Zulko** [comment]
Yes Numpy should make a lot of good to the project!
